// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4J9FuWSNOSg5WoXMLQpTThIVBt-ydmVg',
    appId: '1:86382184397:web:fe5e94014d9f4731716684',
    messagingSenderId: '86382184397',
    projectId: 'moneyapp-ba2cb',
    authDomain: 'moneyapp-ba2cb.firebaseapp.com',
    storageBucket: 'moneyapp-ba2cb.appspot.com',
    measurementId: 'G-9S4QCF71RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXDK479V8SPvT6O16IivC4xAXzCKIJ4pw',
    appId: '1:86382184397:android:0ae5f886c0d379ab716684',
    messagingSenderId: '86382184397',
    projectId: 'moneyapp-ba2cb',
    storageBucket: 'moneyapp-ba2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW0gbOV0O0rTGJ9tPYrQP2Dsl-vD7PYWs',
    appId: '1:86382184397:ios:a34e44dd3cc81803716684',
    messagingSenderId: '86382184397',
    projectId: 'moneyapp-ba2cb',
    storageBucket: 'moneyapp-ba2cb.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW0gbOV0O0rTGJ9tPYrQP2Dsl-vD7PYWs',
    appId: '1:86382184397:ios:e89b09319e176381716684',
    messagingSenderId: '86382184397',
    projectId: 'moneyapp-ba2cb',
    storageBucket: 'moneyapp-ba2cb.appspot.com',
    iosBundleId: 'com.example.moneyTracker.RunnerTests',
  );
}
